apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: django-app

spec:
  containers:
    - name: postgres
      image: "postgres:13"
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres-config
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: postgres-config
        - name: "POSTGRES_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-config
      # volumeMounts:
      #     - name: postgres-storage
      #       mountPath: /var/lib/postgresql/db-data
      # volumes:
      #   - name: postgres-storage
      #     persistentVolumeClaim:
      #       claimName: postgres-pv-claim