# FROM python:3.10-slim-buster

# WORKDIR /django_cont
# COPY . .
# # COPY Pipfile Pipfile
# # RUN apt install python3-pip
# RUN pip install pipenv
# RUN pipenv install
# RUN pipenv install --system
# # RUN apt install pipenv
# # RUN pip install pyscopg2-binary
# # RUN apt install python3-dev libpq-dev
# # RUN pip install psycopg2
# RUN pipenv install django
# RUN pipenv shell
# # RUN python3 manage.py migrate
# # RUN python3 manage.py runserver



# EXPOSE 4567
# CMD ["pipenv", "python3", "-m" , "django", "runserver", "--host=0.0.0.0", "--port=4567"]